import Head from 'next/head'
import { Page } from '../../components/Page'
import { useRouter } from 'next/router'

const ParagraphDetail = ({ data }: { data: string[] }) => {
  const router = useRouter()
  const { name } = router.query

  const content = data.filter(paragraph => paragraph.includes(name![0]))
  return (
    <Page
      headerContent={<h1>Hello, Chess!</h1>}
      footerContent={<h2>Play with Voypost</h2>}
    >
      <Head>
        <title>Chess24 challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2>{name}</h2>
      {content}
    </Page>
  )
}

export default ParagraphDetail
