import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Page } from '../components/Page'

const Home: NextPage = () => {
  return (
    <Page
      headerContent={<h1>Hello, Chest!</h1>}
      footerContent={<h2>Play with Voypost</h2>}
    >
      <Head>
        <title>Chess24 challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      page content
    </Page>
  )
}

export default Home
